#!/usr/bin/env python3
"""Regenerates the launcher icon and the TV banner from the game's own art.

Both are vector drawables made of one-pixel rectangles, so the icon on the Google
TV home screen is the *same* grey tabby, at the same sixteen-bit resolution, as
the cat in the game. Nothing here is hand-maintained: the cat comes from
`CronchArt.kt`, the colours from `TheCroncher.kt` and the lettering from
`Font.kt`, so the art cannot drift from the game.

    python3 scripts/make-icons.py

Writes app/src/main/res/drawable/ic_launcher.xml and banner.xml.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CORE = os.path.join(ROOT, "core/src/main/kotlin/com/yash/thecroncher/core")
RES = os.path.join(ROOT, "app/src/main/res/drawable")


def read(path):
    with open(os.path.join(CORE, path)) as f:
        return f.read()


def grid(name):
    """A single-frame grid out of CronchArt.kt, by name."""
    art = read("theme/CronchArt.kt")
    block = art[art.index(f"val {name} = listOf("):]
    return re.findall(r'"([^"]+)"', block[:block.index("\n    )")])


def palette():
    """Every `name = 0xAARRGGBB.toInt(),` in the theme file."""
    theme = read("theme/themes/TheCroncher.kt")
    found = {}
    for name, value in re.findall(r"(\w+)\s*=\s*0x([0-9A-Fa-f]{8})\.toInt\(\)", theme):
        found.setdefault(name, "#" + value.upper())
    return found


INK = {
    "F": "catFur", "D": "catStripe", "L": "catMuzzle", "E": "catEarInner",
    "N": "catNose", "Y": "catEye", "P": "catPupil", "M": "catMouth",
    "i": "highlight",
    "1": "treatTriangle", "2": "treatSquare", "3": "treatFish", "4": "treatStar",
    "5": "treatShade", "6": "catnipLeaf", "7": "catnipVein",
}


def glyphs():
    """The 5x7 bitmap font, read straight out of Font.kt."""
    font = read("ui/Font.kt")
    out = {}
    for char, rows in re.findall(r"put\('(.)', arrayOf\((.*?)\)\)", font, re.S):
        out[char] = [r for r in re.findall(r'"([^"]*)"', rows)]
    return out


def runs(rows, wanted):
    """Horizontal runs of one ink, as (x, y, width) — fewer, longer rects."""
    for y, row in enumerate(rows):
        x = 0
        while x < len(row):
            if row[x] != wanted:
                x += 1
                continue
            start = x
            while x < len(row) and row[x] == wanted:
                x += 1
            yield start, y, x - start


def path_for(rows, ink, scale, ox=0, oy=0):
    parts = []
    for x, y, w in runs(rows, ink):
        px, py = ox + x * scale, oy + y * scale
        parts.append(f"M{px},{py}h{w * scale}v{scale}h{-w * scale}z")
    return "".join(parts)


def paths(rows, colours, scale, ox=0, oy=0):
    out = []
    for ink in sorted({c for row in rows for c in row if c not in ". "}):
        slot = INK.get(ink)
        if slot is None:
            raise SystemExit(f"no colour mapped for ink '{ink}'")
        data = path_for(rows, ink, scale, ox, oy)
        out.append(f'    <path\n        android:fillColor="{colours[slot]}"\n'
                   f'        android:pathData="{data}" />')
    return out


def text_rows(text, glyph_map):
    """Renders a line of text into an ASCII grid using the in-game font."""
    height = 7
    rows = []
    for row in range(height):
        line = ""
        for i, ch in enumerate(text):
            glyph = glyph_map.get(ch.upper(), ["     "] * height)
            line += glyph[row].replace("#", "4") + "."
        rows.append(line)
    return rows


def vector(width, height, body):
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by scripts/make-icons.py from the game\'s own art. Do not\n'
        '     hand-edit: change CronchArt.kt or TheCroncher.kt and run it again. -->\n'
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        f'    android:width="{width}dp"\n'
        f'    android:height="{height}dp"\n'
        f'    android:viewportWidth="{width}"\n'
        f'    android:viewportHeight="{height}">\n\n'
        + "\n\n".join(body) + "\n\n</vector>\n"
    )


def main():
    cat = grid("CAT_DOWN")
    colours = palette()
    font = glyphs()
    background = colours["background"]

    # --- launcher icon: the face, as large as it will go on a 108dp tile ---
    scale = 6                     # 16 * 6 = 96, leaving a 6dp margin all round
    body = [f'    <path\n        android:fillColor="{background}"\n'
            f'        android:pathData="M0,0h108v108h-108z" />']
    body += paths(cat, colours, scale, ox=6, oy=6)
    with open(os.path.join(RES, "ic_launcher.xml"), "w") as f:
        f.write(vector(108, 108, body))

    # --- banner: the face, the wordmark, and a line of treats ---
    body = [f'    <path\n        android:fillColor="{background}"\n'
            f'        android:pathData="M0,0h320v180h-320z" />']
    body += paths(cat, colours, 6, ox=26, oy=46)
    for line, (text, size, ox, oy) in enumerate([
        ("THE", 3, 142, 58),
        ("CRONCHER", 3, 142, 86),
    ]):
        rows = text_rows(text, font)
        body += [f'    <path\n        android:fillColor="{colours["toyBell"]}"\n'
                 f'        android:pathData="{path_for(rows, "4", size, ox, oy)}" />']
    # the four treats, exactly as they appear in the maze
    for i, treat in enumerate(
        ["TREAT_TRIANGLE", "TREAT_SQUARE", "TREAT_FISH", "TREAT_STAR"]
    ):
        body += paths(grid(treat), colours, 4, ox=142 + i * 36, oy=112)
    with open(os.path.join(RES, "banner.xml"), "w") as f:
        f.write(vector(320, 180, body))

    print("wrote ic_launcher.xml and banner.xml", file=sys.stderr)


if __name__ == "__main__":
    main()
