#!/usr/bin/env bash
# Generate wrapper shims for the Android CLI tools.
#
# Why: some SDK tooling writes an analytics file to $HOME/.android regardless of
# ANDROID_USER_HOME. These shims pin HOME to a sandbox inside .toolchain for the
# duration of the tool's run only — so the user's real HOME is never touched, and
# their shell's HOME is left alone (overriding it globally would break git, ssh...).
set -euo pipefail

PROJECT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
TOOLCHAIN="$PROJECT_ROOT/.toolchain"
BIN="$TOOLCHAIN/bin"
SDK="$TOOLCHAIN/android-sdk"

mkdir -p "$BIN"

make_shim() {
    local name="$1" target="$2"
    cat > "$BIN/$name" <<SHIM
#!/usr/bin/env bash
# Auto-generated by scripts/make-wrappers.sh — do not edit.
TOOLCHAIN="\$( cd "\$( dirname "\${BASH_SOURCE[0]}" )/.." && pwd )"
export HOME="\$TOOLCHAIN"
export ANDROID_USER_HOME="\$TOOLCHAIN/.android"
export ANDROID_SDK_HOME="\$TOOLCHAIN"
export ANDROID_AVD_HOME="\$TOOLCHAIN/.android/avd"
export ANDROID_EMULATOR_HOME="\$TOOLCHAIN/.android"
export ANDROID_SDK_ROOT="\$TOOLCHAIN/android-sdk"
export ANDROID_HOME="\$TOOLCHAIN/android-sdk"
export JAVA_HOME="\$TOOLCHAIN/jdk-17"
exec "$target" "\$@"
SHIM
    chmod +x "$BIN/$name"
}

make_shim sdkmanager  "\$TOOLCHAIN/android-sdk/cmdline-tools/latest/bin/sdkmanager"
make_shim avdmanager  "\$TOOLCHAIN/android-sdk/cmdline-tools/latest/bin/avdmanager"
make_shim adb         "\$TOOLCHAIN/android-sdk/platform-tools/adb"
make_shim emulator    "\$TOOLCHAIN/android-sdk/emulator/emulator"

echo "wrappers written to $BIN:"
ls -1 "$BIN"
