#!/usr/bin/env python3
"""Regenerates the launcher icon, the TV banner and the Play Store art from the
game's own art.

Everything is drawn from the same pixel grids, so the icon on the Google TV home
screen is the *same* grey tabby, at the same sixteen-bit resolution, as the cat
in the game. Nothing here is hand-maintained: the face comes from `CatFaces.kt`,
its colours from `GreyTabby.kt`, the treats and their colours from `CronchArt.kt`
and `TheCroncher.kt`, and the lettering from `Font.kt`, so the art cannot drift
from the game.

    python3 scripts/make-icons.py

Writes
    app/src/main/res/drawable/ic_launcher.xml         vector launcher icon
    app/src/main/res/drawable-xhdpi/banner.png        320x180  TV home-screen banner
    app/src/main/res/drawable-xxxhdpi/banner.png      640x360  same, for 4K panels
    store/icon-512.png                                Play listing hi-res icon
    store/tv-banner-1280x720.png                      Play listing TV banner
    store/feature-graphic-1024x500.png                Play listing feature graphic

The banner is a raster rather than a vector on purpose: Android asks for a
320x180 xhdpi bitmap, and lint objects to a vector this detailed. The PNGs are
written with the standard library alone — the sealed toolchain has no Pillow.
"""
import os
import re
import struct
import sys
import zlib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CORE = os.path.join(ROOT, "core/src/main/kotlin/com/yash/thecroncher/core")
RES = os.path.join(ROOT, "app/src/main/res")
STORE = os.path.join(ROOT, "store")


def read(path):
    with open(os.path.join(CORE, path)) as f:
        return f.read()


def grid(name, source="theme/CronchArt.kt"):
    """A single-frame grid out of a Kotlin file, by name."""
    art = read(source)
    block = art[art.index(f"val {name} = listOf("):]
    return re.findall(r'"([^"]+)"', block[:block.index("\n    )")])


def colours_in(source):
    """Every `name = 0xAARRGGBB.toInt(),` in a Kotlin file."""
    found = {}
    for name, value in re.findall(r"(\w+)\s*=\s*0x([0-9A-Fa-f]{8})\.toInt\(\)", read(source)):
        found.setdefault(name, "#" + value.upper())
    return found


def palette():
    """The theme's colours plus the grey tabby's, under the ink slot names."""
    found = colours_in("theme/themes/TheCroncher.kt")
    for slot, colour in colours_in("theme/cats/GreyTabby.kt").items():
        found["cat." + slot] = colour
    return found


# The ink alphabet, as documented on CatBreed and CronchArt.
INK = {
    "F": "cat.fur", "D": "cat.marking", "L": "cat.muzzle", "E": "cat.earInner",
    "N": "cat.nose", "Y": "cat.eye", "P": "cat.pupil", "M": "cat.mouth",
    "i": "highlight",
    "1": "treatTriangle", "2": "treatSquare", "3": "treatFish", "4": "treatStar",
    "5": "treatShade", "6": "catnipLeaf", "7": "catnipVein",
}


def cat_face():
    """The Croncher's face: the tabby grid, which GreyTabby.kt points at."""
    face = re.search(r"face\s*=\s*CatFaces\.(\w+)", read("theme/cats/GreyTabby.kt")).group(1)
    return grid(face, "theme/cats/CatFaces.kt")


def glyphs():
    """The 5x7 bitmap font, read straight out of Font.kt."""
    font = read("ui/Font.kt")
    out = {}
    for char, rows in re.findall(r"put\('(.)', arrayOf\((.*?)\)\)", font, re.S):
        out[char] = [r for r in re.findall(r'"([^"]*)"', rows)]
    return out


def runs(rows, wanted):
    """Horizontal runs of one ink, as (x, y, width) — fewer, longer rects."""
    for y, row in enumerate(rows):
        x = 0
        while x < len(row):
            if row[x] != wanted:
                x += 1
                continue
            start = x
            while x < len(row) and row[x] == wanted:
                x += 1
            yield start, y, x - start


def path_for(rows, ink, scale, ox=0, oy=0):
    parts = []
    for x, y, w in runs(rows, ink):
        px, py = ox + x * scale, oy + y * scale
        parts.append(f"M{px},{py}h{w * scale}v{scale}h{-w * scale}z")
    return "".join(parts)


def paths(rows, colours, scale, ox=0, oy=0):
    out = []
    for ink in sorted({c for row in rows for c in row if c not in ". "}):
        slot = INK.get(ink)
        if slot is None:
            raise SystemExit(f"no colour mapped for ink '{ink}'")
        data = path_for(rows, ink, scale, ox, oy)
        out.append(f'    <path\n        android:fillColor="{colours[slot]}"\n'
                   f'        android:pathData="{data}" />')
    return out


def text_rows(text, glyph_map):
    """Renders a line of text into an ASCII grid using the in-game font."""
    height = 7
    rows = []
    for row in range(height):
        line = ""
        for i, ch in enumerate(text):
            glyph = glyph_map.get(ch.upper(), ["     "] * height)
            line += glyph[row].replace("#", "4") + "."
        rows.append(line)
    return rows


def vector(width, height, body):
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by scripts/make-icons.py from the game\'s own art. Do not\n'
        '     hand-edit: change CatFaces.kt or GreyTabby.kt and run it again. -->\n'
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        f'    android:width="{width}dp"\n'
        f'    android:height="{height}dp"\n'
        f'    android:viewportWidth="{width}"\n'
        f'    android:viewportHeight="{height}">\n\n'
        + "\n\n".join(body) + "\n\n</vector>\n"
    )


class Canvas:
    """An RGB bitmap drawn with axis-aligned rectangles, written out as PNG."""

    def __init__(self, width, height, background):
        self.width, self.height = width, height
        self.pixels = [[background] * width for _ in range(height)]

    def rect(self, x, y, w, h, colour):
        for py in range(max(y, 0), min(y + h, self.height)):
            row = self.pixels[py]
            for px in range(max(x, 0), min(x + w, self.width)):
                row[px] = colour

    def grid(self, rows, colours, scale, ox=0, oy=0):
        """Paints a CronchArt grid, one rect per horizontal run of each ink."""
        for ink in sorted({c for row in rows for c in row if c not in ". "}):
            slot = INK.get(ink)
            if slot is None:
                raise SystemExit(f"no colour mapped for ink '{ink}'")
            for x, y, w in runs(rows, ink):
                self.rect(ox + x * scale, oy + y * scale, w * scale, scale, colours[slot])

    def text(self, rows, colour, scale, ox=0, oy=0):
        for x, y, w in runs(rows, "4"):
            self.rect(ox + x * scale, oy + y * scale, w * scale, scale, colour)

    def write(self, path):
        def chunk(kind, data):
            body = kind + data
            return struct.pack(">I", len(data)) + body + struct.pack(">I", zlib.crc32(body))

        raw = bytearray()
        for row in self.pixels:
            raw.append(0)                      # filter type: none
            for colour in row:
                raw += bytes.fromhex(colour[3:9])  # "#AARRGGBB" -> RGB
        header = struct.pack(">IIBBBBB", self.width, self.height, 8, 2, 0, 0, 0)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "wb") as f:
            f.write(b"\x89PNG\r\n\x1a\n")
            f.write(chunk(b"IHDR", header))
            f.write(chunk(b"IDAT", zlib.compress(bytes(raw), 9)))
            f.write(chunk(b"IEND", b""))


# The banner composition, in 320x180 units: the face, the wordmark, and a line
# of treats. Every raster is this same picture at a whole-number multiple, so the
# pixel art stays crisp at any size.
BANNER_W, BANNER_H = 320, 180
BANNER_CAT = (6, 26, 46)                       # scale, x, y
BANNER_WORDMARK = [("THE", 3, 142, 58), ("CRONCHER", 3, 142, 86)]
BANNER_TREATS = (4, 142, 112, 36)              # scale, x, y, spacing
TREATS = ["TREAT_TRIANGLE", "TREAT_SQUARE", "TREAT_FISH", "TREAT_STAR"]


def paint_banner(canvas, colours, font, k, ox=0, oy=0):
    """Draws the banner at k times its unit size, offset to (ox, oy)."""
    cat = cat_face()
    scale, x, y = BANNER_CAT
    canvas.grid(cat, colours, scale * k, ox + x * k, oy + y * k)
    for text, size, x, y in BANNER_WORDMARK:
        canvas.text(text_rows(text, font), colours["toyBell"], size * k, ox + x * k, oy + y * k)
    scale, x, y, gap = BANNER_TREATS
    for i, treat in enumerate(TREATS):
        canvas.grid(grid(treat), colours, scale * k, ox + (x + i * gap) * k, oy + y * k)


def banner_png(colours, font, k, path):
    canvas = Canvas(BANNER_W * k, BANNER_H * k, colours["background"])
    paint_banner(canvas, colours, font, k)
    canvas.write(path)


def main():
    cat = cat_face()
    colours = palette()
    font = glyphs()
    background = colours["background"]
    written = []

    # --- launcher icon: the face, as large as it will go on a 108dp tile ---
    scale = 6                     # 16 * 6 = 96, leaving a 6dp margin all round
    body = [f'    <path\n        android:fillColor="{background}"\n'
            f'        android:pathData="M0,0h108v108h-108z" />']
    body += paths(cat, colours, scale, ox=6, oy=6)
    path = os.path.join(RES, "drawable/ic_launcher.xml")
    with open(path, "w") as f:
        f.write(vector(108, 108, body))
    written.append(path)

    # --- in-app TV banner: 320x180 at xhdpi as Android asks, and 2x for 4K ---
    for density, k in [("xhdpi", 1), ("xxxhdpi", 2)]:
        path = os.path.join(RES, f"drawable-{density}/banner.png")
        banner_png(colours, font, k, path)
        written.append(path)

    # --- Play Store listing art ---
    path = os.path.join(STORE, "tv-banner-1280x720.png")
    banner_png(colours, font, 4, path)
    written.append(path)

    # 512x512 icon: the face at x28 (448px) with a 32px margin all round.
    canvas = Canvas(512, 512, background)
    canvas.grid(cat, colours, 28, 32, 32)
    path = os.path.join(STORE, "icon-512.png")
    canvas.write(path)
    written.append(path)

    # 1024x500 feature graphic: the banner at x3 (960x540), centred, with the
    # 20px of empty background above and below cropped away.
    canvas = Canvas(1024, 500, background)
    paint_banner(canvas, colours, font, 3, ox=(1024 - BANNER_W * 3) // 2, oy=-20)
    path = os.path.join(STORE, "feature-graphic-1024x500.png")
    canvas.write(path)
    written.append(path)

    for path in written:
        print("wrote", os.path.relpath(path, ROOT), file=sys.stderr)


if __name__ == "__main__":
    main()
